### ISSUE TITLE
Results of methods much lower than reported elsewhere

### ISSUE THREAD

**Issue by blaz-r** [AI4RS/UCD#1]
Hi, 
Thanks for the great work. 
I am wondering how exactly were the results for the methods obtained, because for most methods the results are much lower than reported in other works. Were they trained and evaluated correctly?

**Comment by EricYu97** [comment]
Hi,
Thanks a lot for your interest in our research.

The results were obtained using the same training criteria (i.e., hyperparameters, datasets). The details of the training and testing details can be found in the ``configs`` directory. We use an identical baseline setting to train and test all the methods on each dataset.

Since the implemented algorithms may be trained using the dedicated hyperparameters and datasets that differ from our implementation, the results can be quite different from our implementation. This is also because we did not apply additional tricks in training and testing the methods that may introduce unfair biases in the experiments.

We are happy to accept other pretrained weights to be displayed and more results to be reported.

**Comment by blaz-r** [comment]
Thank you for the explanation. That probably explains the low results.
